load("//bazel:defs.bzl", "wersalka_binary")

wersalka_binary(
    name = "hello",
    srcs = "hello.w",
    deps = ["//stdlib"],
)

wersalka_binary(
    name = "closure",
    srcs = "closure.w",
    #    deps = ["//stdlib"],
)

wersalka_binary(
    name = "tuples",
    srcs = "tuples.w",
    #    deps = ["//stdlib"],
)
